<a href="https://colab.research.google.com/github/lucasfernandesf1/market-basket-analysis-apriori/blob/main/supermarket1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving supermarket.arff to supermarket.arff

In [2]:
from scipy.io import arff
import pandas as pd

In [3]:
data = arff.loadarff('supermarket.arff')

In [5]:
df = pd.DataFrame(data[0])

In [6]:
df.head()

,department1,department2,department3,department4,department5,department6,department7,department8,department9,grocery misc,...,department208,department209,department210,department211,department212,department213,department214,department215,department216,total
0,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'high'
1,b't',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
2,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
3,b't',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'
4,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',...,b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'?',b'low'

In [9]:
##transformar em strings
for col in df.columns:
    df[col] = df[col].astype(str)

In [10]:
## limpando os valores
for col in df.columns:
    df[col] = df[col].str.replace("b'", "")
    df[col] = df[col].str.replace("'", "")

In [12]:
df.head()

,department1,department2,department3,department4,department5,department6,department7,department8,department9,grocery misc,...,department208,department209,department210,department211,department212,department213,department214,department215,department216,total
0,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,high
1,t,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
2,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
3,t,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
4,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low

In [15]:
df = df.loc[:, ~df.columns.str.contains('department')]

Foram removidas colunas do tipo "department", pois não representam itens de compra relevantes para análise de associação.

In [16]:
df.shape

(4627, 106)

In [17]:
df = df.loc[:, (df == 't').any()]

Foram removidas colunas sem ocorrência de compras (sem valores 't'), pois não contribuem para a geração de regras de associação.

In [19]:
df.shape

(4627, 100)

In [20]:
df.to_csv('supermarket_clean.csv', index=False)

In [21]:
from google.colab import files
files.download('supermarket_clean.csv')